name: Build and Release R2CSharp

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and publish
      run: dotnet publish src/R2CSharp.App/R2CSharp.App.csproj -r linux-arm64 -c Release -o ./publish
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/r2csharp
        token: ${{ secrets.GITHUB_TOKEN }} 